### ISSUE TITLE
Typo in client/pscheduler/api_connect.py

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/psconfig#140]
From Wayne Jackson:

> File “/usr/lib/python3/dist-packages/psconfig/client/pscheduler/api_connect.py”
> Contains “http_resonse”  at line 56 instead of “http_response”
>  
>  
> As a result of the above my test configurations which resides on our Central Archive did not populate to our test host. Also, we lost communication (443) back to the Central Archive for test results.
> I made the change in the Python code but thought you may like to know for your reference and future deliveries.
>  
>  
> V/R,
> Wayne Jackson
> Code 423
> EOSDIS
> (480)540-3279
> [Wayne.p.jackson@nasa.gov](mailto:Wayne.p.jackson@nasa.gov)

**Comment by szymontrocha** [comment]
Observed probably the same while suporting deployment in RENATER:

But when i restart the psconfig-pscheduler-agent, still get the error : 

    2024-09-27 16:03:45 ERROR pid=27466 prog=_run_start line=135 guid=3378e376-464d-4588-bbb1-37efd03bee8e pscheduler_assist_url=https://localhost/pscheduler msg=Problem initializing task_manager: build_err_msg() got an unexpected keyword argument 'http_resonse'

**Comment by mfeit-internet2** [comment]
This is already fixed in 0eca5dc5d6b43dc75585cc5e7124e55aa88cdd9d.
