### ISSUE TITLE
esmond agent to control IP authentication

### ISSUE THREAD

**Issue by arlake228** [perfsonar/psconfig#17]
Suggestion from user:

> There might be a better place to make feature requests, but I'm sitting here adding 40+ individual "authenticate by IP" entries to esmond (again) because I reinstalled a host that participates in a large mesh.  
> 
> It occurs to me, it would dramatically simplify these authentication setups if I could say (perhaps in the meshconfig-agent.conf file?) something along the lines of esmond_authenticate=yes  So that any hosts that are a part of the "mesh configured" testing could be automatically authenticated by IP (and IPv6).  
> 
> I realize you'd have to do lookups for both A and AAAA records and somehow feed that to esmond.  But this would reduce the complexity of configuring these meshes (and making them green up) by a massive amount.  
> 
> I'd recommend of course that the default setting be esmond_authenticate=no so the default behavior is the (presumably safer) option where you have to manage authentication manually.
> 
> thoughts?
> 
> Sincerely,
> Casey Russell

**Comment by igarny** [comment]
IMHO: It would be nice to have a parser of the pSconfig, that generates the commands for Esmond, so that the administrator just executes it on his Esmond server.

**Comment by arlake228** [comment]
No longer valid
