### ISSUE TITLE
IPv6 addresses not properly bracketed in URLs

### ISSUE THREAD

**Issue by arlake228** [perfsonar/psconfig#2]
The pscheduler agent generates pscheduler URLs that are not properly bracketed. It is likely this is somewhere in the perl-shared library, but is very obvious in the log messages when it occurs. It is also likely this is not a new issue, just that logging is better since the code that generates that URL is from 4.0.

**Comment by arlake228** [comment]
This turned out to be more involved than I though, but i think i have a fix. It looks like the problem is somewhere in LWP::UserAgent or one of the libraries it uses. It's very easy to recreate (try any test with a source IPv6 address). Our code properly puts brackets around the IPv6 address but LWP::UserAgent strips them out. There also doesn't seem to be a good way to keep them around (tried double square brackets and backslashes with no luck). 

This is not the first time LWP has given us IPv6 fits. We already use some odd IPv6Glue library to make it work and that seems to no longer do the trick. I think the time has come to migrate away from LWP. I have added a patch to use Mojo::UserAgent which is part of the perl-Mojolicious lib we already include in 4.1 (JSON::Validator needs it). It has a bunch of nice features, is newer and implement IPv6 correctly. Pretty easy transition, just a couple method name changes to account for a few places.

Changes are committed and RPMs built. Will close once testbed looks ok.

**Comment by arlake228** [comment]
Looks like it's working properly.

**Comment by akurov** [comment]
Are built RPMs available for testing somewhere (for CentOS 7)?
