### ISSUE TITLE
Memory leak in maddash agent

### ISSUE THREAD

**Issue by arlake228** [perfsonar/psconfig#20]
After each run of the maddash agent the memory is growing. Eventually the process runs out of memory and the agent stops working properly. We have seen this on the dev testbed multiple times and I am able to recreate locally using the maddash-agent.json file from the dev mesh. The sequence of events appears to be:

1. Things run fine for awhile

2. The logs start showing this message:

Error expanding check plugin vars: Unable to run jq command(jq if .test.spec.udp==true then    "udp" else    "tcp" end): Cannot allocate memory during fork at /vagrant/bin/../lib/perfSONAR_PS/Utils/JQ.pm line 77.

3. This leaves a bunch of pipes open which eventually leads to this message:

Error expanding check plugin vars: Unable to run jq command(jq .test.spec."ip-version"==6): Too many open files: pipe() at /vagrant/bin/../lib/perfSONAR_PS/Utils/JQ.pm line 77.

Restarting the maddash-agent returns things to step 1.

**Comment by arlake228** [comment]
The problem with this appears to have been caused by a known leak in the IPC::Run library. This library was being used to make calls to `jq`. Switching to IPC::Run3 very clearly fixed the issue. Prior to the switch I could get an increase of memory by multiple MBs each time the agent ran (and by updating check-interval in /etc/perfsonar/psconfig/maddash-agent.json i could have it run very frequently). After the switch to IPC::Run3 the memory usage stabalized. According to IPC::Run3 one of the advantaged of the library over IPC:Run is:

> better: does not fall prey to Perl closure leaks

Source: http://search.cpan.org/dist/IPC-Run3/lib/IPC/Run3.pm

**Comment by arlake228** [comment]
Adding to upstream pipeline for @tonin or @vvidic to update Debian dependency in the libperfsonar-perl package to IPC::Run3 instead of IPC::Run. IPC::Run is still a dependency in other packages (e.g. libperfsonar-regulartesting-perl) and should be left as is for now. It can be completely removed from libperfsonar-perl though and replaced with IPC::Run3. See 96400718cc8652f584c1237a0bd81c5772675e46 for change i made to spec file

**Comment by tonin** [comment]
I did the change on the Debian package.  I see we still have the IPC::Run dependency in perfsonar-toolkit-perl, is it actually required? (we don't have it in Debian)

**Comment by arlake228** [comment]
That dependency is indeed required. When we completely are able to remove the libperfsonar-regulartesting-perl it can go away, but it is still needed for the toolkit GUI.

Closing issue since this appears to be resolved now.
