### ISSUE TITLE
lead-bind-address property

### ISSUE THREAD

**Issue by igarny** [perfsonar/psconfig#27]
Hi Andy,

in the documentation: http://docs.perfsonar.net/release_candidates/4.1b1/psconfig_templates_vars.html#lead-bind-address-variable
the example with `reference` is invalid

2018/07/27 10:16:26 ERROR pid=31538 prog=perfSONAR_PS::PSConfig::BaseAgent::_process_psconfig line=378 guid=1bee0a4a-d6af-4862-9e17-e1911e0a78dc config_src=remote config_url=http://172.17.0.1/rrzemesh-1.json category=psconfig_schema_validation_error expanded=0 transformed=0 json_path=/groups/bw_group msg=anyOf failed: Properties not allowed: addresses, reference. Properties not allowed: reference. Properties not allowed: reference.
2018/07/27 10:16:26 ERROR pid=31538 prog=main::__ANON__ line=131 guid=1bee0a4a-d6af-4862-9e17-e1911e0a78dc msg=Died: Can't call method "checksum" on an undefined value at /usr/lib/perfsonar/bin/../lib/perfSONAR_PS/PSConfig/BaseAgent.pm line 316.

My environment is Ubuntu 16:
ii  perfsonar-psco 4.1\~5.b1-1   all          pSConfig pScheduler Agent
ii  perfsonar-psco 4.1~5.b1-1   all          pSConfig pScheduler Development L

**Comment by igarny** [comment]
forgot to mention, that the fallback statement does not appear to be valid

**Comment by igarny** [comment]
It appears the `reference` property is accepted at `task` spec.

**Comment by arlake228** [comment]
This was a misunderstanding of docs, closing.

**Comment by arlake228** [comment]
Still a problem with throughput tests, need to remove checks for one it can detect pscheduler on one side.
