### ISSUE TITLE
Debian packages for perfsonar-psconfig

### ISSUE THREAD

**Issue by tonin** [perfsonar/psconfig#3]
We can start working on the Debian packages and add the debian/jessie branch to this repository. As usual the [RPM specfile](https://github.com/perfsonar/psconfig/blob/master/perfsonar-psconfig.spec) is the starting point.

**Comment by vvidic** [comment]
We also need to create init scripts because Ubuntu trusty does not have systemd.

**Comment by vvidic** [comment]
Packages running on all Debian/Ubuntu variants.
