### ISSUE TITLE
Add hosts metadata - lat lon, organization

### ISSUE THREAD

**Issue by dimm0** [perfsonar/psconfig#35]
Hi!
I'm trying to wrap my head around the new psconfig JSON format, and I don't see fields like organization and lat-lon etc for addresses. Where will those go? How can I get those into esmond database now?

**Comment by arlake228** [comment]
You can add those in the `_meta` field of the `address` objects. No specific requirements on how you name them, it is up to how you want your application to ingest them. If you want them to make there way to esmond then you also need to set the `reference` field in the task objects as discussed in the documentation here: http://docs.perfsonar.net/psconfig_templates_advanced.html#setting-the-pscheduler-reference-field. It will appear in the esmond metadata as `pscheduler-reference-FIELD` where FIELD is the name of the key you put in the reference object.

**Comment by dimm0** [comment]
Terrific, thanks!
