### ISSUE TITLE
Case-sensitivity of match-addresses

### ISSUE THREAD

**Issue by arlake228** [perfsonar/psconfig#41]
It appears that maybe the pscheduler-agent is case sensitive to match-addresses when comparing the results from reverse DNS to local interfaces. For example, reverse DNS returns Perfsonar-XSEDE.loni.org so using the all lowercase version in the template causes pscheduler not to match anything thus not to create any tests on the host. I have not confirmed 100% that this is the issue, but it appears to be given that adding the all lower case version to pscheduler-agent.json fixes things.

**Comment by mfeit-internet2** [comment]
Comparisons of those should definitely be case-insensitive.
