### ISSUE TITLE
Report syntax error details in `psconfig validate`

### ISSUE THREAD

**Issue by arlake228** [perfsonar/psconfig#42]
The `psconfig validate` command does not seem to report the specifics of a syntax error like `psconfig translate` does. It would be good to pass these through so it is easier to pinpoint issues.

**Comment by apertome** [comment]
Is this going to happen in the near future? I have had a couple regressions recently with the PWA publisher that I could have caught prior to doing a new release, if we had this.

**Comment by arlake228** [comment]
This no longer appears to be an issue, the errors in question are getting pass through like translate does.

@apertome the issue you are talking about is #29. I will take a look at that one next.
