### ISSUE TITLE
psconfig with JSON::XS

### ISSUE THREAD

**Issue by vvidic** [perfsonar/psconfig#5]
Installing JSON::XS (required by the toolkit) seems to change the behaviour of psconfig plugins:

```
$ psconfig maddash-viz-plugins 

/usr/lib/perfsonar/psconfig/visualization/ps-graphs.json is not valid. The following errors were encountered: 
    JSON Path: /http-get-opts/dest/required
    Error: Expected boolean - got JSON::XS::Boolean.
```

**Comment by arlake228** [comment]
Note to self: Seems to be a lot of discussion about problems like this online. Apparently the behavior changes between versions of JSON::XS, so may want to double-check versions each OS uses. Based on a quick Google search, seems to be consensus that this is a bug in JSON::XS where its not properly getting converted to a JSON boolean.

**Comment by arlake228** [comment]
On CentOS 7 perl-JSON-XS is installed and does not cause problems. Version of perl-JSON-XS is 3.01-2.

@vvidic: What OS are you seeing this on and what version of perl-JSON-XS? I may try to get some vagrant descriptions setup for some debian VMs so I can more easily test this kinda thing in the future.

**Comment by vvidic** [comment]
On Thu, Mar 01, 2018 at 11:55:52AM -0800, Andrew R. Lake wrote:
> On CentOS 7 perl-JSON-XS is installed and does not cause problems.
> Version of perl-JSON-XS is 3.01-2.
> 
> @vvidic: What OS are you seeing this on and what version of
> perl-JSON-XS? I may try to get some vagrant descriptions setup for
> some debian VMs so I can more easily test this kinda thing in the
> future.

This was Debian/jessie with libjson-xs-perl 2.340-1+b2.  Unfortunately
we might not be able to build a new version because this is a binary
perl package that usually breaks on Ubuntu side (different perl
version).

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
On Thu, Mar 01, 2018 at 11:55:52AM -0800, Andrew R. Lake wrote:
> On CentOS 7 perl-JSON-XS is installed and does not cause problems.
> Version of perl-JSON-XS is 3.01-2.
> 
> @vvidic: What OS are you seeing this on and what version of
> perl-JSON-XS? I may try to get some vagrant descriptions setup for
> some debian VMs so I can more easily test this kinda thing in the
> future.

This was on Debian 8 jessie with libjson-xs-perl v2.340-1+b2.
Now I got it working by forcing the JSON::PP lib instead:

$ export PERL_JSON_BACKEND='JSON::PP'
$ psconfig maddash-viz-plugins 

The following pSConfig MaDDash agent visualization plugins are
installed:

ps-traceroute-viewer
ps-graphs

If we could only place something like this in one of the library
headers before JSON.pm is imported:

BEGIN {
    if (eval "require JSON::XS" && $JSON::XS::VERSION < 3.0) {
        $ENV{PERL_JSON_BACKEND} = 'JSON::PP';
    }
}
use JSON qw(from_json);

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by arlake228** [comment]
Heh, I was looking at that env variable this morning as well and was just trying to cook-up a block like you shared, thanks. I am trying to find a good location for that block. Assigning to myself to do so and will hand back to you (@vvidic) once I am done to try building in Debian.

**Comment by vvidic** [comment]
On Thu, Apr 05, 2018 at 01:32:16PM +0000, Andrew R. Lake wrote:
> Heh, I was looking at that env variable this morning as well and was
> just trying to cook-up a block like you shared, thanks. I am trying to
> find a good location for that block. Assigning to myself to do so and
> will hand back to you (@vvidic) once I am done to try building in
> Debian.

I used /usr/share/perl5/perfSONAR_PS/Client/Utils.pm because the first
JSON import was from there, not sure if that is the best place...

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by arlake228** [comment]
A lot of the command-line utilities import JSON directly before any of the perfSONAR_PS modules, so it doesn't work for those. I was originally trying perfSONAR_PS::Client::PSConfig::BaseConnect for similar reasons since all the things that call validate are subclasses of that. It worked for some things but not for others depending on the order of imports. This seems pretty fragile since over time its going to be pretty easy to trip-up the import order.

I am starting to lean more towards trying to set the environment variable on Debian 8  as opposed to doing it in code since that seems to be more consistent. That requires some changes on Debian8, specifically:

1. Creating a file like`/etc/systemd/system/psconfig-pscheduler-agent.service.d/env.conf` and `/etc/systemd/system/psconfig-pscheduler-maddash.service.d/env.conf` that updates the unit file to set PERL_JSON_BACKEND as follows:

```
[Service]
Environment= PERL_JSON_BACKEND=JSON::PP
```

2. Creating files in /etc/profile.d/ that set PERL_JSON_BACKEND for shells (i.e. the command-line clients)

3. We may need something similar to #1 for the configdaemon in the toolkit since it write a file

4. We may need to throw the BEGIN block at the top of the cgi scripts that return the JSON version of the host status

Maybe we should have a quick chat after the call in a couple minutes.

**Comment by vvidic** [comment]
On Thu, Apr 05, 2018 at 07:45:57AM -0700, Andrew R. Lake wrote:
> A lot of the command-line utilities import JSON directly before any of
> the perfSONAR_PS modules, so it doesn't work for those. I was
> originally trying perfSONAR_PS::Client::PSConfig::BaseConnect for
> similar reasons since all the things that call validate are subclasses
> of that. It worked for some things but not for others depending on the
> order of imports. This seems pretty fragile since over time its going
> to be pretty easy to trip-up the import order.

Here is an updated version of the BEGIN block that tries to reload
JSON if loaded with XS already:

BEGIN {
    if (eval "require JSON::XS" && $JSON::XS::VERSION < 3.0) {
        if ($INC{'JSON.pm'} && JSON::backend()->isa("JSON::XS")) {
            use Symbol;
            Symbol::delete_package('JSON');
            delete $INC{'JSON.pm'};
        }

        $ENV{PERL_JSON_BACKEND} = 'JSON::PP';
        require JSON;
        JSON->import;
    }
}

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by arlake228** [comment]
Change committed. Need to rebuild perl-shared to get change. Assign to vvidic to build debian packages and verify.

**Comment by vvidic** [comment]
On Thu, Apr 05, 2018 at 06:58:39PM +0000, Andrew R. Lake wrote:
> Change committed. Need to rebuild perl-shared to get change. Assign to vvidic to build debian packages and verify.

Thanks, did a quick test on all supported variants and it seems to
be working, so I think you can close the issue.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr
