### ISSUE TITLE
have extended output for parsed tasks

### ISSUE THREAD

**Issue by igarny** [perfsonar/psconfig#60]
Hi Andy,

Here I am looking for an extended diagnostic message for these cases:
```
2019/03/28 10:16:02 WARN pid=25584 prog=perfSONAR_PS::PSConfig::PScheduler::Agent::_run_end line=218 guid=18e23b83-4b9d-4241-8523-511a87bf35b5 msg=Problem adding test throughput(test1.rrze->test2.rrze), continuing with rest of config: HTTP/1.1 403 FORBIDDEN
: Task forbidden by limits:
Hints:
  requester: fd00:638:a000:3502::48
  server: fd00:638:a000:3502::48
Identified as everybody, local-interfaces, bogons
Classified as default, hostiles, friendlies
Application: Hosts we don't want running any tests
  Group 1: Limit 'never' failed: Forced failure
  Group 1: Want all, 0/1 passed, 1/1 failed: FAIL
  Group 1: Failed; stopping here.
  Application FAILS
    Failed - Stop Forced
Proposal does not meet limits
```
My inquiry is not about the specific problem, but for an extended output from psconfig to diagnose it.
I see you have  **guid=** there. My guess it is based on the parsing of the mesh configuraiton.
My call is for the possibility to see/find these failures in the mesh configuration with the guid reference included.

Perhaps you could extend the output of **psconfig pscheduler-tasks** with list of failed tasks.
Any other solution will fit as long I am able to read through these faulty config items.

**Comment by mfeit-internet2** [comment]
Is `throughput(test1.rrze->test2.rrze)` not enough to nail down which test was causing the problem?

**Comment by igarny** [comment]
well these are only the source and destination of a test:
but these could differ:
- mesh source with different schedules
- ip stack: are you able to tell if it is about the IPv4 or IPv6 tests just from the requester address or are you making assumptions

Of course it is not the end of the world, if we do not have that

**Comment by arlake228** [comment]
I think what you want is already logged, you are just looking at a different log. You've probably seen this but just including it for completeness, the logs are described in some detail here: http://docs.perfsonar.net/psconfig_pscheduler_agent.html#reading-the-logs

The message you are providing looks like it is from the "agent" log which is intended to be a little bit more concise and get you pointed in the right direction with some initial information. I think the information you want is in the "transaction log" at /var/log/perfsonar/psconfig-pscheduler-agent-transactions.log which logs every single interaction with pscheduler including the JSON it sent and received. The log file contains a lot of info, but is structured in a manner intended to be easy to grep/parse. For example you might have luck with something like the following:

```
cat /var/log/perfsonar/psconfig-pscheduler-agent-transactions.log | grep test1.rrze | grep test2.rrze | grep guid=18e23b83-4b9d-4241-8523-511a87bf35b5 | grep action=create
```

My ultimate goal of having the logs be parsable is that we can have utilities to help with stuff like this. There may be additional context we need to add, but I suspect something like the above can get you closer to what you want.
