### ISSUE TITLE
Using twping tool for latency and rtt how should I configure the schedule so it runs continuously.

### ISSUE THREAD

**Issue by micruzz82** [perfsonar/psconfig#86]
I have a question on how to configure the psconfig file to setup the schedule for running latency test with twping and also rtt using twping.

I have read the document and it looks like if you use latencybg, that runs continuously by default.

However what can I configure in the schedule if I need to make the twping for latency or rtt to also run continuously by default?

    "tests": 
        "twamp_test": {
            "type": "latency",
            "spec": {
                "source": "{% address[0] %}",
                "dest": "{% address[1] %}",
                "packet-interval": 0.1,
                "packet-count": 600
            }
        },
        "rtt_test": {
            "type": "rtt",
            "spec": {
                "source": "{% address[0] %}",
                "dest": "{% address[1] %}",
                "packet-interval": 0.1,
                "packet-count": 600
            }
        }

    "schedules": { 
       "every_1_second": {
            "repeat": "PT1S",
            "slip": "PT1S",
            "sliprand": true
        }
    }

    "tasks":
        "twamp_task": {
            "group": "twamp_group",
            "test": "twamp_test",
           "schedule": "every_1_second",
            "archives": ["esmond_archive"],
			"tools": ["twping"]
        },
        "rtt_task": {
            "group": "rtt_group",
            "test": "rtt_test",
           "schedule": "every_1_second",
            "archives": ["esmond_archive"],
			"tools": ["twping"]
        }

Is the above config the right way to achieve this for both tests using twping?

**Comment by arlake228** [comment]
TWAMP does not currently have a tool that supports continuous mode as OWAMP does. We have an issue open on this here: https://github.com/perfsonar/owamp/issues/19

Something like what you have is probably as close as you can get currently.

**Comment by micruzz82** [comment]
Thank you @arlake228 closing this if it's already covered.
